Transform: AWS::Serverless-2016-10-31

Parameters:
  Realm:
    Type: String
    Description: DNS name of the api (e.g. tabbychat-api.andrewohara.io)

Globals:
  Function:
    Runtime: java11
    MemorySize: 2048
    Environment:
      Variables:
        REALM: !Ref Realm
        USERS_TABLE_NAME: !Ref Users
        CONTACTS_TABLE_NAME: !Ref Contacts
        MESSAGES_TABLE_NAME: !Ref Messages
        AUTH_TABLE_NAME: !Ref Authorizations

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      #      CorsConfiguration:
      #        AllowCredentials: true
      #        AllowHeaders: [ Authorization ]
      #        AllowMethods: [ GET, POST ]
      #        AllowOrigins: [ !Ref FrontendHost ]
      #        ExposeHeaders: [ '*' ]
      DisableExecuteApiEndpoint: true

  ApiHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Timeout: 10
      Handler: io.andrewohara.tabbychat.ApiLambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Users
        - DynamoDBCrudPolicy:
            TableName: !Ref Contacts
        - DynamoDBCrudPolicy:
            TableName: !Ref Messages
        - DynamoDBCrudPolicy:
            TableName: !Ref Authorizations
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  Contacts:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ownerId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: ownerId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE

  Messages:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ownerId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: ownerId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE

  Authorizations:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: value
          AttributeType: S
      KeySchema:
        - AttributeName: value
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires
        Enabled: true
